clone:
  git:
    image: plugins/git
    depth: 1
pipeline:
  build_step_test:
    image: plugins/docker
    username: ihealth
    password: iHealthStrategy2018
    registry: harbor.ihealthcn.com
    repo: harbor.ihealthcn.com/tonytest/swift-snail
    mirror: 'https://registry.docker-cn.com'
    tag:
      - '${DRONE_BUILD_NUMBER}'
      - latest
    dockerfile: docker/test/Dockerfile
    when:
      branch: develop
      event: push

rancher:
    image: peloton/drone-rancher
    url: 'http://rancher.ihealthcn.com/v2-beta/projects/1a3707'
    access_key: 5C75CB261869728029C1
    secret_key: xVuKLMhDnLamuw4raChKV4FhakdzVEimkxrVFgyC
    service: owenTest/SwiftSnailTest
    docker_image: 'harbor.ihealthcn.com/tonytest/swift-snail:latest'
    batch_size: 1
    timeout: 600
    confirm: true
    when:
      branch: develop
      event: push
