export const MedicineUsage = {
  Qd: { label: 'Qd', means: '每日一次' },
  Bid: { label: 'Bid', means: '每日二次' },
  Tid: { label: 'Tid', means: '每日三次' },
  Qid: { label: 'Qid', means: '每日四次' },
  ac: { label: 'ac', means: '饭前' },
  pc: { label: 'pc', means: '饭后' },
  am: { label: 'am', means: '上午' },
  pm: { label: 'pm', means: '下午' },
  sos: { label: 'sos', means: '需要时' },
  prn: { label: 'prn', means: '必要时，长期备用医嘱' },
  st: { label: 'st', means: '立即' },
  pN: { label: 'pN', means: '每晚' },
  hs: { label: 'hs', means: '睡前' },
  Q6h: { label: 'Q6h', means: '每6小时一次' },
}
export const usageArray = (() => {
  const rst = []
  Object.keys(MedicineUsage).forEach((k) => {
    rst.push(MedicineUsage[k])
  })
  return rst
})()
export const Medicines = [
  {
    category: '钙离子通道拮抗剂',
    name: '硝苯地平片',
    spec: '10mg×100片/瓶',
    dosage: [5, 7.5, 10, 12.5, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '硝苯地平缓释片',
    spec: '20mg×30片/盒',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '尼群地平片',
    spec: '10mg×100片/瓶',
    dosage: [5, 10, 15, 20, 25, 30],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '尼卡地平缓释片（佩尔）',
    spec: '40mg*30片',
    dosage: [20, 40, 60, 80],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '非洛地平缓释片(波依定)',
    spec: '5mg×10片/盒',
    dosage: [5, 7.5, 10, 12.5, 15],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '苯磺酸氨氯地平片(络活喜)',
    spec: '5mg×7片/盒',
    dosage: [5, 7.5, 10, 12.5, 15],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '拉西地平片（乐息平）',
    spec: '4mg*7片/盒',
    dosage: [2, 4, 5, 5.5, 6, 7],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '硝苯地平控释片(拜新同)',
    spec: '30mg×7片/盒',
    dosage: [15, 30, 45, 60, 75, 90],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸贝尼地平片(可力洛)',
    spec: '8mg×7片/盒',
    dosage: [4, 8, 12, 16],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸地尔硫卓片(合心爽)',
    spec: '30mg×20片/盒',
    dosage: [15, 30, 45, 60],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '马来酸左旋氨氯地平片（玄宁）',
    spec: '2.5mg×7/9/14片/盒',
    dosage: [1.25, 2.5, 3.75, 5],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '左旋氨氯地平（施慧达）',
    spec: '2.5mg×14/片/盒',
    dosage: [1.25, 2.5, 3.75, 5],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸地尔硫卓缓释胶囊(Ⅱ)(合贝爽) ',
    spec: '90mg*10粒/盒',
    dosage: [45, 90, 135, 180],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸地尔硫卓控释胶囊（芊克）',
    spec: '90mg*6粒/盒',
    dosage: [45, 90, 135, 180],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸地尔硫卓片(恬尔心)',
    spec: '30mg×40片/盒',
    dosage: [15, 30, 45, 60, 75, 90],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '尼群地平片（南国）',
    spec: '10mg*100片/瓶',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '尼群地平片（华南）',
    spec: '10mg*100片/瓶',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '尼群地平片(石药资寿)',
    spec: '10mg*100片/瓶',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸乐卡地平片(再宁平) ',
    spec: '10mg*7片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸乐卡地平片(圣华曦)',
    spec: '10mg*7片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸维拉帕米片(华南牌)',
    spec: '40mg*30片/盒',
    dosage: [20, 40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸维拉帕米缓释片(缓释异博定) ',
    spec: '240mg*10片/盒',
    dosage: [120, 240, 360, 480],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸维拉帕米缓释片(异博定) ',
    spec: '40mg*30片/盒',
    dosage: [20, 40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: '钙离子通道拮抗剂',
    name: '盐酸维拉帕米片(松树牌) ',
    spec: '40mg*30片/盒',
    dosage: [20, 40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '双氢克脲塞（双克、氢氯噻嗪片）',
    spec: '25mg×100片/瓶',
    dosage: [12.5, 25, 37.5, 50, 62.5, 75, 87.5, 100],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '吲达帕胺片',
    spec: '2.5mg×30片/盒',
    dosage: [1.25, 2.5, 3.75, 5],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '吲达帕胺缓释片（钠催离）',
    spec: '1.5mg×30片/盒',
    dosage: [1.5, 3],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '螺内酯（信谊）',
    spec: '20 mg×100片/瓶',
    dosage: [10, 20, 30, 40, 60, 80],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '螺内酯（丰海）',
    spec: '20 mg×100片/瓶',
    dosage: [20, 40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '螺内酯（民生）',
    spec: '20 mg×100片/瓶',
    dosage: [20, 40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '托拉塞米',
    spec: '10mg×6/12/24片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '呋塞米（天津力生）',
    spec: '20 mg×100片/瓶',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '呋塞米片(光辉)',
    spec: '20 mg×100片/瓶',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '呋塞米片(亚邦药业)',
    spec: '20 mg×100片/瓶',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '呋塞米片(三才)',
    spec: '20 mg×100片/瓶',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: '利尿剂',
    name: '阿米洛利',
    spec: '10mg×12/14/28片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '盐酸普萘洛尔片',
    spec: '10mg×100片/瓶',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '阿替洛尔片',
    spec: '25mg×100片/瓶',
    dosage: [25, 50, 75, 100],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '酒石酸美托洛尔片',
    spec: '25mg×20片/盒',
    dosage: [25, 50, 75, 100],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '琥珀酸美托洛尔缓释片(倍他乐克)',
    spec: '47.5mg×7片/盒',
    dosage: [23.75, 47.5],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '盐酸阿罗洛尔片(阿尔马尔)',
    spec: '10mg×10片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '富马酸比索洛尔片(康忻)',
    spec: '5mg×10片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '富马酸比索洛尔片(博苏)',
    spec: '5mg×10片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '卡维地洛片(络德)',
    spec: '10mg×20片/盒',
    dosage: [12.5, 15, 17.5, 20, 22.5, 25],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '特拉唑嗪',
    spec: '2mg×14片/28片/盒',
    dosage: [1, 2, 3, 4],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '盐酸拉贝洛尔片(迪赛诺)',
    spec: '50mg×30片/盒',
    dosage: [50, 100, 150, 200, 250, 300, 350, 400],
    usage: usageArray,
  },
  {
    category: 'α、β受体阻滞剂（洛尔）',
    name: '盐酸哌唑嗪片(信谊)',
    spec: '1mg/2mg×100片/盒',
    dosage: [0.25, 0.5, 0.75, 1, 1.25],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '卡托普利片',
    spec: '25mg×100片/瓶',
    dosage: [12.5, 25, 37.5, 50],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '马来酸依那普利片',
    spec: '10mg×16片/盒',
    dosage: [5, 10, 15, 20, 25, 30],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '福辛普利钠片(蒙诺)',
    spec: '10mg×14片/盒',
    dosage: [10, 15, 20, 25, 30],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '盐酸贝那普利片(洛汀新)',
    spec: '10mg×14片/盒',
    dosage: [10, 15, 20, 25, 30],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '雷米普利片(瑞素坦)',
    spec: '5mg×14片/盒',
    dosage: [2.5, 5, 7.5, 10, 12.5, 15],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '培哚普利片(雅施达)',
    spec: '4mg×30片/盒',
    dosage: [4, 6, 8, 10, 12.5, 15],
    usage: usageArray,
  },
  {
    category: '无数据',
    name: '咪哒普利片(达爽)',
    spec: '10mg×10片/袋',
    dosage: [5, 10, 15, 20, 25, 30],
    usage: usageArray,
  },
  {
    category: 'ARB',
    name: '氯沙坦钾片(科素亚(0.1g))',
    spec: '100mg×7片/盒',
    dosage: [50, 75, 100, 125, 150, 175, 200],
    usage: usageArray,
  },
  // {
  //   category: 'ARB',
  //   name: '缬沙坦胶囊(丽珠维可)',
  //   spec: '10.54元/盒',
  //   dosage: '80～160mg',
  //   usage: usageArray,
  // },
  {
    category: 'ARB',
    name: '替米沙坦片(美卡素)',
    spec: '80mg×7片/盒',
    dosage: [40, 60, 80, 100, 120],
    usage: usageArray,
  },
  {
    category: 'ARB',
    name: '坎地沙坦西酯（必洛斯）',
    spec: '8mg×7片/盒',
    dosage: [8, 12, 16, 20],
    usage: usageArray,
  },
  {
    category: 'ARB',
    name: '奥美沙坦酯片',
    spec: '20mg×7片/盒',
    dosage: [10, 20, 30, 40],
    usage: usageArray,
  },
  {
    category: 'ARB',
    name: '厄贝沙坦片(安博维)',
    spec: '150mg×7片/盒',
    dosage: [150, 300],
    usage: usageArray,
  },
  {
    category: 'ARB',
    name: '缬沙坦(代文)',
    spec: '',
    dosage: [40, 80, 160],
    usage: usageArray,
  },
  {
    category: 'ACEI',
    name: '赖诺普利',
    spec: '10mg*14片/盒',
    dosage: [5, 10, 15, 20],
    usage: usageArray,
  },
  {
    category: '复方制剂',
    name: '缬沙坦氨氯地平片',
    spec: '80mg/5mg×7片/盒',
    dosage: [],
    usage: usageArray,
  },
  {
    category: '复方制剂',
    name: '氯沙坦钾氢氯噻嗪片（海捷亚）',
    spec: '50mg/12.5mg×7片/盒',
    dosage: [],
    usage: usageArray,
    // instructions: '1/日',
    // humanWords: '每次大小各1片',
  },
  {
    category: '复方制剂',
    name: '厄贝沙坦氢氯噻嗪片',
    spec: '150mg/12.5mg×7片/盒',
    dosage: [],
    usage: usageArray,
    // instructions: '1/日',
    // humanWords: '每次大小各1片',
  },
  {
    category: '复方制剂',
    name: '复方降压片',
    spec: '30片/盒',
    dosage: [],
    usage: usageArray,
    // instructions: '1/日',
    // humanWords: '每次大小各1片',
  },
  {
    category: '多效复方制剂',
    name: '马来酸依那普利叶酸片',
    spec: '10mg/0.8mg×7片/盒',
    dosage: [],
    usage: usageArray,
    // instructions: '1/日',
    // humanWords: '每次大小各1片',
  },
  {
    category: '多效复方制剂',
    name: '氨氯地平阿托伐他汀钙片',
    spec: '5mg/10mg×7片/盒',
    dosage: [],
    usage: usageArray,
    // instructions: '1/日',
    // humanWords: '每次大小各1片',
  },
  {
    category: '多效复方制剂',
    name: '复方利血平氨苯蝶啶片 (北京降压 0 号)',
    spec: '12.5mg*10/30片/盒',
    dosage: [12.5],
    usage: usageArray,
  },
  {
    category: '多效复方制剂',
    name: '复方阿米洛利(安利亚、武都力)',
    spec: '24片/盒',
    dosage: [],
    usage: usageArray,
  },
]

export const MedicinesOption = (() => {
  const rst = []
  Medicines.forEach((m) => {
    const temp = {
      value: m.name,
      label: m.name,
      children: [],
    }
    const tempUsage = []
    m.usage.forEach((u) => {
      tempUsage.push({
        value: u.label,
        label: u.label,
        title: u.means,
      })
    })

    m.dosage.forEach((d) => {
      const dosageTemp = {
        value: d,
        label: `${d}mg`,
        children: tempUsage,
      }
      temp.children.push(dosageTemp)
    })
    rst.push(temp)
  })
  return rst
})()
